//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassMate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassMate()
        {
            this.ClassMateFoods = new HashSet<ClassMateFood>();
            this.ClassMateVacations = new HashSet<ClassMateVacation>();
            this.IdealSaturdayClassMates = new HashSet<IdealSaturdayClassMate>();
            this.SongGenres = new HashSet<SongGenre>();
            this.ClassMateResults = new HashSet<ClassMateResult>();
            this.ClassMateResults1 = new HashSet<ClassMateResult>();
        }
    
        public int ClassMateId { get; set; }
        public string email { get; set; }
        public string fullname { get; set; }
        public string loginhash { get; set; }
        public string symbol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassMateFood> ClassMateFoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassMateVacation> ClassMateVacations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdealSaturdayClassMate> IdealSaturdayClassMates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongGenre> SongGenres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassMateResult> ClassMateResults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassMateResult> ClassMateResults1 { get; set; }
    }
}
