//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassMateResult
    {
        public int Id { get; set; }
        public string score { get; set; }
        public Nullable<int> classmateId1 { get; set; }
        public Nullable<int> classmateid2 { get; set; }
    
        public virtual ClassMate ClassMate { get; set; }
        public virtual ClassMate ClassMate1 { get; set; }
    }
}
