//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassMateSongGenre
    {
        public int ClassMateSongGenreId { get; set; }
        public string ClassMateId { get; set; }
        public string SongGenreId { get; set; }
    }
}
