//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdealSaturdayClassMate
    {
        public int IdealSaturdayClassMateId { get; set; }
        public int ClassMateId { get; set; }
        public int IdealSaturdayId { get; set; }
    
        public virtual ClassMate ClassMate { get; set; }
        public virtual IdealSaturday IdealSaturday { get; set; }
    }
}
