//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdealSaturday
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IdealSaturday()
        {
            this.IdealSaturdayClassMates = new HashSet<IdealSaturdayClassMate>();
        }
    
        public int IdealSaturdayId { get; set; }
        public string idealSaturday1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdealSaturdayClassMate> IdealSaturdayClassMates { get; set; }
    }
}
